flowchart TD
    A[Mobile App]
    B[Website]
    C[NestJS REST Endpoints]
    D[NestJS GraphQL Endpoints]
    E[Database]

    A -->|Requests| C
    B -->|Requests| C
    A -->|Requests| D
    B -->|Requests| D
    C -->|Database queries| E
    C -->|Publishes events| D
    D -->|Pushes GraphQL/WS Subscription updates| A
    D -->|Pushes GraphQL/WS Subscription updates| B