
services:
  postgres:
    image: postgres:15
    container_name: canvassing-postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER-canvassing_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-canvassing_dev}
      POSTGRES_DB: ${POSTGRES_DB-canvassing_dev}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: