export const DEFAULT_POSTGRES_USER = 'canvassing_dev';
export const DEFAULT_POSTGRES_PASSWORD = 'canvassing_dev';
export const DEFAULT_POSTGRES_DB = 'canvassing_dev';
export const DEFAULT_POSTGRES_PORT = 5432;
export const DATA_SOURCE = 'DATA_SOURCE';

export const ORGANIZATIONS_REPOSITORY = 'ORGANIZATIONS_REPOSITORY';
export const ADDRESSES_REPOSITORY = 'ADDRESSES_REPOSITORY';
export const ADDRESSLISTS_REPOSITORY = 'ADDRESSLISTS_REPOSITORY';
export const ANSWERS_REPOSITORY = 'ANSWERS_REPOSITORY';
export const QUESTIONS_REPOSITORY = 'QUESTIONS_REPOSITORY';
export const QUESTIONNAIRE_REPOSITORY = 'QUESTIONNAIRE_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';

export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
